config/routes.rb
###
# Copyright (C) 2012 Juergen Helmers - All Rights Reserved
# You may not use, distribute and modify this code under any
# circumstance without the written permission of the author.
#
# Juergen Helmers <juergen.helmers@gmail.com>
###

Screeningandor::Application.routes.draw do

  resources :well_comparisons do
    member do
      get 'compare_with_control'
    end
  end

  get "send_images/show_file_by_send"

  resources :organisms

  resources :analytic_results

  resources :screen_settings

  devise_for :users

  resources :users, :except => [:new, :show] do
    member do
      get 'approve'
      get 'disable'
      get 'grant_admin'
      get 'deny_admin'
      get 'grant_receive_system_mail'
      get 'deny_receive_system_mail'
    end
  end

  resources :welcome, :only => :index
  
  resources :workingwells do
    member do
      get 'add_to_compare'
      get 'remove_from_compare'
    end
    collection do
      get 'clear_comparison_cart'
    end
  end

  match 'searches', to: 'workingwells#index', via: :get

  match 'jqueryfiletree/:id/content' => 'jqueryfiletree#content'#, :as => :content
  resources :jqueryfiletree do
    collection do
      post 'content'
    end
  end

  resources :workingplates do
    member do
      get 'omeroimport'
      post 'import'
      get 'generate_uuid_file'
    end
  end

  resources :masterwells, :only => [:new, :create, :show ]

  resources :masterplates

  resources :screens

  resources :well_names
  resources :well_uuids
  resources :metadata_record_values
  #resources :well_mature_sanger_ids
  #resources :well_precursor_accessions
  #resources :well_catalog_numbers
  #resources :well_mature_sequences


  authenticate :user do
    mount Resque::Server.new, :at => "/resque", :as => 'resque'
  end

  root :to => 'welcome#index'

end

app/models/workingplate.rb
###
# Copyright (C) 2012 Juergen Helmers - All Rights Reserved
# You may not use, distribute and modify this code under any
# circumstance without the written permission of the author.
#
# Juergen Helmers <juergen.helmers@gmail.com>
###

class Workingplate < ActiveRecord::Base
  require 'iconv'
  require 'fileutils'
  require 'uuidtools'

  belongs_to :masterplate
  belongs_to :user
  has_many   :workingwells, :dependent => :destroy

  serialize :htd_file_info, Hash
  
  attr_accessor :mp_id, :image_file
  
  before_create :set_uuid

  scope :with_username, -> { joins(:user).order("workingplates.id").select("workingplates.*,users.username AS user_name") }
  
  def set_uuid
    self.uuid = UUIDTools::UUID.timestamp_create().to_s
  end

  def self.image_type(file)
      if file.present?
        # store file header in string
        command = Escape.shell_command(["#{APP_CONFIG['exiv2']}", '-pa', file])
        result = %x[#{command}]
        if result.include? "Andor"
          return "Andor"
        elsif result.include? "MetaMorph"
          return "MetaMorph"
        else
          return "unknown"
        end
      else
        return "no file given"
      end
  end

  def self.read_htd_file(rfp)
    dir = File.dirname(rfp)                                    # get the directory name from uuid files full path
    raw_htd_file = File.open(Dir[dir + "/**/*.{htd,HTD}"][0])  # read the first HTD file in uuid file's directory
    htd_entry = {}                                             # initialize an empty hash for file content
    raw_htd_file.each do |line|                                # read the file object line by line
      ic = Iconv.new('UTF-8//IGNORE', 'UTF-8')                 # replace invalid utf-8 characters (required!)
      line = ic.iconv(line)
      line.chop!                                               # remove any new line characters
      line.gsub!('"', "").sub!(",", "\t")                      # remove extra quotes and replace only the first comma with a tab
      key, value = line.split("\t")                            # split at tab and assign to key and value
      htd_entry[key] = value                                   # save the key value pair in hash
    end
    return htd_entry                                           # return the complete hash
  end

  def self.get_channel_names(htd_file_info)
    channel_names = {}                                         # instantiate a new has to hold channel names
    htd_file_info.each do |key, value|                         # loop over the htd_file_info hash
      if key.include? "WaveName"                               # check if the key contains "WaveName"
        channel_names[key] = value.gsub(/^\s|\s+$/, "")        # if yes add the new key-value pair to the new hash, remove leading/trailing spaces
      end
    end
    return channel_names
  end
  
  def self.resque_options(dir,workingplate)
    first_image_file = Dir[dir + "/**/*.{tif,TIF}"][0]          # get the first image file from directory
    image_type = self.image_type(first_image_file)              # determine the image_type
    options = {
        "dir" => dir,                                           # image directory
        "workingplate_id" => workingplate.id,                   # workingplate_id
        "rails_env" => Rails.env                                # Rails environment name
    }

    if image_type == "Andor"
      unless workingplate.imported || workingplate.processing
        options['image_type'] = "Andor"                          # image_type
      end
      return options
    elsif image_type == "MetaMorph"
      unless workingplate.imported || workingplate.processing
        options['image_type']      = "MetaMorph"                                        # image_type
        options['rails_env']       = Rails.env                                          # Rails environment name
        options['number_channels'] = workingplate.htd_file_info['NWavelengths'].strip   # save the number of image channels
        options['channel_names']   = self.get_channel_names(workingplate.htd_file_info)  # get the list of channels
      end
      logger.debug "helmerj: options: #{options}"
      return options
    else
      options['image_type'] = "other"
      return options
    end

  end
end

app/controllers/workingplates_controller.rb
###
# Copyright (C) 2012 Juergen Helmers - All Rights Reserved
# You may not use, distribute and modify this code under any
# circumstance without the written permission of the author.
#
# Juergen Helmers <juergen.helmers@gmail.com>
###

class WorkingplatesController < ApplicationController
  # GET /workingplates
  # GET /workingplates.json
  require 'rexml/document'
  require 'uuidtools'
  require 'fileutils'


  before_filter :authenticate_user!
  
  def index
    if params[:term].present?    # for autosuggest look up
      @workingplates = Workingplate.order(:label).where("label ilike ?", "%#{params[:term]}%")
      render json: @workingplates.map(&:label)
    else
      if params[:me] == "true"
        @workingplates = Workingplate.with_username.where(:user_id => current_user.id).paginate(:page => params[:page], :per_page => 20)
      elsif params[:status] == "imported"
        @workingplates = Workingplate.with_username.where("user_id = ? AND imported = ?", "#{current_user.id}", true ).paginate(:page => params[:page], :per_page => 20)
      elsif params[:status] == "processing"
        @workingplates = Workingplate.with_username.where("user_id = ? AND processing = ?", "#{current_user.id}", true ).paginate(:page => params[:page], :per_page => 20)
      elsif params[:status] == "unprocessed"
        @workingplates = Workingplate.with_username.where("user_id = ? AND processing = ? AND imported =?", "#{current_user.id}", false, false ).paginate(:page => params[:page], :per_page => 20)
      else
        @workingplates = Workingplate.with_username.paginate(:page => params[:page], :per_page => 20)
      end
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @workingplates }
      end

    end
  end

  # GET /workingplates/1
  # GET /workingplates/1.json
  def show
    # @workingplate = Workingplate.find(params[:id])
    @workingplate = Workingplate.joins(:user).joins(:masterplate).select("workingplates.*, users.username AS user_name, masterplates.label AS masterplate_label").includes(:workingwells => :metadata_records).find(params[:id])
    @htd = @workingplate.htd_file_info.to_a
    # @workingwells = @workingplate.workingwells.order("id ASC")
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @workingplate }
    end
  end

  # GET /workingplates/new
  # GET /workingplates/new.json
  def new
    @workingplate = Workingplate.new
    @masterplate = Masterplate.find_by_id(params[:mp_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @workingplate }
    end
  end

  # GET /workingplates/1/edit
  def edit
    @workingplate = Workingplate.find(params[:id])
    @masterplate = Masterplate.find_by_id(@workingplate.masterplate_id)
  end

  def labels
    @workingplate_labels = Workingplate.order(:label).where("label like = ?", "%#{params[:term]}%")
    render json: @workingplate_labels.map(&:label)
  end

  # POST /workingplates
  # POST /workingplates.json
  def create
    # get the parent masterplate object
    @workingplate = WorkingplateBuilder.new(params, current_user.id).build

    respond_to do |format|
      if @workingplate.save
        format.html { redirect_to @workingplate, notice: 'Workingplates successfully created.' }
        format.json { render json: @workingplate, status: :created, location: @workingplate }
      else
        format.html { render action: "new" }
        format.json { render json: @workingplate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /workingplates/1
  # PUT /workingplates/1.json
  def update
    @workingplate = Workingplate.find(params[:id])
    @masterplate = Masterplate.find_by_id(@workingplate.masterplate_id)

    respond_to do |format|
      if @workingplate.update_attributes(params[:workingplate])
        format.html { redirect_to @workingplate, notice: 'Workingplate was successfully updated.', :me => true }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        @masterplate = Masterplate.find_by_id(@workingplate.masterplate_id)
        format.json { render json: @workingplate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workingplates/1
  # DELETE /workingplates/1.json
  def destroy
    @workingplate = Workingplate.find(params[:id])
    @workingplate.destroy

    respond_to do |format|
      format.html { redirect_to workingplates_url, :me => true }
      format.json { head :no_content }
    end
  end


  # GET /workingplates/1/omeroimport
  def omeroimport
    # change permissions to own all files by group rubyonrails to make them accessible to the application

    # rename all directories in the root file tree to replace white-spaces with underscores
    # jqueryfiletree will crash otherwise
    Dir["#{APP_CONFIG['remote_file_root_directory']}" + "/**/"].each {|x| File.rename x, x.gsub(" ", "_") if File.directory? x}
    @workingplate = Workingplate.find(params[:id])
  end

  def import
    @workingplate = Workingplate.find(params[:id])
    @rfp = params[:workingplate][:remote_file_path]                     # get the file path and UUID file name from form field
    file_uuid = File.basename(@rfp).gsub(".uuid", "")                   # remove the suffix => UUID
    dir = File.dirname(@rfp)                                            # get the full path
    if file_uuid.present? && @workingplate.uuid == file_uuid            # in case of UUID and if UUID matches that of workingplate
      htd_file_info = Workingplate.read_htd_file(@rfp)
      @workingplate.update_attributes(:remote_file_path => @rfp,        # save the full path to workingplate record
                                      :htd_file_info => htd_file_info)  # save the htd file information hash
      @workingplate.save                                                # save the updated record

      options = Workingplate.resque_options(dir,@workingplate)

      unless options['image_type'] == "other"
        logger.debug "helmerj: options before worker: #{options}"
        Resque.enqueue(RewriteOmeXml, options)                    # enqueue the new job
        @workingplate.update_attributes(:processing => 1)         # set the processing flag
        @workingplate.save                                        # save the update
        respond_to do |format|
          format.html { redirect_to @workingplate, notice: "Image files have been successfully added to the processing queue." }
          format.json { head :no_content }
        end
      else
        redirect_to omeroimport_workingplate_path, :alert => "The image files in the source directory are neither Andor nor MetaMorph files!" and return
      end
    else
      redirect_to omeroimport_workingplate_path, :alert => "#{@rfp} The Workingplate UUID does not match the UUID from the image directory or no UUID file was chosen." and return
    end
  end

  def generate_uuid_file
    @workingplate = Workingplate.find(params[:id])                        # get the current workingplate
    file = ''                                                             # instantiate a new file
    file << @workingplate.uuid                                            # use the workingplate UUID as file name
    send_data file, :filename => @workingplate.uuid, :type => 'text/uuid' # send the file to the browser
  end

end

app/helpers/workingplates_helper.rb
###
# Copyright (C) 2012 Juergen Helmers - All Rights Reserved
# You may not use, distribute and modify this code under any
# circumstance without the written permission of the author.
#
# Juergen Helmers <juergen.helmers@gmail.com>
###

module WorkingplatesHelper

  def return_color_value(value)
    int = value.to_f
    gamma = 1
    if int > 0 && int <= 0.1
      return "rgba(0,52,241,#{gamma})"
    elsif int > 0.1 && int <= 0.2
      return "rgba(0,83,255,#{gamma})"
    elsif int > 0.2 && int <= 0.3
      return "rgba(0,180,255,#{gamma})"
    elsif int > 0.3 && int <= 0.4
      return "rgba(23,255,234,#{gamma})"
    elsif int > 0.4 && int <= 0.5
      return "rgba(136,255,119,#{gamma})"
    elsif int > 0.5 && int <= 0.6
      return "rgba(233,255,25,#{gamma})"
    elsif int > 0.6 && int <= 0.7
      return "rgba(255,164,0,#{gamma})"
    elsif int > 0.7 && int <= 0.8
      return "rgba(255,67,0,#{gamma})"
    elsif int > 0.8 && int <= 0.9
      return "rgba(225,0,0,#{gamma})"
    elsif int > 0.9 && int <= 1
      return "rgba(128,0,0,#{gamma})"
    end
  end

  def heatmap_color_for value # [0,1]
    h = ((1 - value.to_f) * 100).round(2)
    s = 100.round(2)
    l = (value.to_f * 50).round(2)
    return "hsl(#{h},#{s}%,#{l}%)"
  end

  def HeatMapColor(value, min, max)
    val = (value - min) / (max - min)
    r = (255 * val).round(0)
    g = (255 * (1 - val)).round(0)
    b = 0

    return "255,#{r},#{g},#{b}"
  end


  def old_return_color_value(value)
    # transparency value
    gamma = 1
    # define start and end color values

    # start color
    yr = 255
    yg = 0
    yb = 0

    # end color
    xr = 0
    xg = 0
    xb = 255

    # number of color steps
    n = 100

    # maximum value

    max = 100
    # calculate the rounded value in percent
    pos=((value.to_f / max.to_f)*100).round

    # calculate the color values

    red = ( xr + ( pos * (( yr - xr )) / ( n - 1 )))
    green = ( xg + (
    pos * (( yg - xg )) / ( n - 1 )))
    blue = ( xb + ( pos * (( yb - xb )) / ( n - 1 )))




    clr = "rgba(#{red},#{green},#{blue},#{gamma})"

    return clr
  end

end

app/views/workingplates/_form.html.haml
-#
  Copyright (C) 2012 Juergen Helmers - All Rights Reserved
  You may not use, distribute and modify this code under any
  circumstance without the written permission of the author.

  Juergen Helmers <juergen.helmers@gmail.com>


= form_for @workingplate, :html => { :class => 'well form-horizontal' } do |f|
  %fieldset
    %legend
      = controller.action_name.capitalize
      Workingplates
    .control-group
      = f.label :label, :class => 'control-label'
      .controls
        = f.text_field :label, :class => 'text_field', :value => "#{@masterplate.label}-A and -B", :disabled => true
    .control-group
    .control-group
      = f.label :description, :class => 'control-label'
      .controls
        = f.text_area :description, :class => 'text_area', :value => @masterplate.description
        = f.hidden_field :mp_id, :value => @masterplate.id
    .form-actions
      = f.submit nil, :class => 'btn btn-mini btn-primary'
      = link_to 'Cancel', workingplates_path, :class => 'btn btn-mini', :me => true

app/views/workingplates/edit.html.haml
-#
  Copyright (C) 2012 Juergen Helmers - All Rights Reserved
  You may not use, distribute and modify this code under any
  circumstance without the written permission of the author.

  Juergen Helmers <juergen.helmers@gmail.com>


= render :partial => 'form'

app/views/workingplates/import.html.haml
-#
  Copyright (C) 2012 Juergen Helmers - All Rights Reserved
  You may not use, distribute and modify this code under any
  circumstance without the written permission of the author.

  Juergen Helmers <juergen.helmers@gmail.com>


%h1 Import

app/views/workingplates/index.html.haml
-#
  Copyright (C) 2012 Juergen Helmers - All Rights Reserved
  You may not use, distribute and modify this code under any
  circumstance without the written permission of the author.

  Juergen Helmers <juergen.helmers@gmail.com>


%h1 Workingplates

%div.filter
  %p
    = link_to "All Workingplates", :action => "index"
    |
    = link_to "My Workingplates", :action => "index", :me => "true"
    |
    = link_to "Currently Processing", :action => "index", :status => "processing"
    |
    = link_to "Imported", :action => "index", :status => "imported"
    |
    = link_to "Unprocessed", :action => "index", :status => "unprocessed"


-if @workingplates.present?

  %table.table.table-striped
    %thead
      %tr
        %th Label
        -#%th Uuid
        %th Created at
        %th Owner
        %th Actions
    %tbody
      - @workingplates.each do |workingplate|
        %tr
          %td= link_to workingplate.label, workingplate_path(workingplate)
          -#%td= workingplate.uuid
          %td= workingplate.created_at.strftime("%Y-%m-%d")
          %td= workingplate.user_name
          %td
            -if current_user && workingplate.user_id == current_user.id || current_user.admin?
              = link_to 'Edit', edit_workingplate_path(workingplate), :class => 'btn btn-mini'
              = link_to 'Destroy', workingplate_path(workingplate), :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-mini btn-danger'
              - if workingplate.imported
                %button.btn.btn-mini.btn-diabled
                  imported
              - elsif workingplate.processing
                = link_to 'Processing', '/resque', :class => 'btn btn-mini btn-warning'
              -else
                = link_to 'Process Images', omeroimport_workingplate_path(workingplate), :class => 'btn btn-success btn-mini'

            -else
              <span class="red">not your plate</span>
  = will_paginate(@workingplates, :class => 'apple_pagination')

-else
  %div.no_record
    %p
      There are currently no workingplates present that match your criteria. Use the "Workingplate" link next to one of your
      =link_to 'masterplates', masterplates_path
      to generate some.

app/views/workingplates/new.html.haml
-#
  Copyright (C) 2012 Juergen Helmers - All Rights Reserved
  You may not use, distribute and modify this code under any
  circumstance without the written permission of the author.

  Juergen Helmers <juergen.helmers@gmail.com>


= render :partial => 'form'

app/views/workingplates/omeroimport.html.haml
-#
  Copyright (C) 2012 Juergen Helmers - All Rights Reserved
  You may not use, distribute and modify this code under any
  circumstance without the written permission of the author.

  Juergen Helmers <juergen.helmers@gmail.com>


= form_for @workingplate, :method => :post, :url => {:action => "import"}, :html => { :class => 'well form-horizontal' } do |f|
  %fieldset
    %legend
      Processing Workingplates
    .control-group
      = f.label :label, :class => 'control-label'
      .controls.down
        = @workingplate.label
    .control-group
      = f.label :description, :class => 'control-label'
      .controls.down
        = @workingplate.description
    .control-group
      = f.label :uuid, :class => 'control-label'
      .controls.down
        = link_to @workingplate.uuid, generate_uuid_file_workingplate_url(@workingplate.id)
        
    .control-group.remote_file_path
      = f.label :remote_file_path, "Path to UUID File", :class => 'control-label'
      .controls
        = f.text_field :remote_file_path, :class => 'text_field path_field'
          
    .control-group
      = f.label "Files", :class => 'control-label'
      .controls
        #fileTree.demo
        .clear
        %p.notice
          Only directories and *.uuid files will be listed.
    
    .form-actions
      = f.submit "Rewrite", :class => 'btn btn-success', :id => "submitButton"
      = link_to 'Cancel', workingplates_path, :class => 'btn', :me => true

- content_for :sidebar_title do
  Rewriting of Image Headers
- content_for :sidebar do
  %p
    In order to connect the saved annotation meta-data with the images acquired, choose the correct UUID file
    located in the same directory the images derived from the workingplate are located in: 
    %ol
      %li
        Use the file-browser to navigate to the directory of images.
      %li
        Click on the correct UUID file and the full path will be inserted into the "Path to UUID File" input field.
      %li
        Compare the name of the UUID file with the UUID displayed in the working-plate "UUID" field directly above the full path input field.
      %li
        Click "Rewrite" to rewrite the image header with an OME/XML header structure.

:javascript
  $(document).ready( function() {
    $('#fileTree.demo').fileTree({
      root: '',
      script: '/jqueryfiletree/content',
      expandSpeed: 1000,
      collapseSpeed: 1000,
      blacklist: ["composite", "montage"]
      }, function(file) {
      $('#workingplate_remote_file_path').val("#{APP_CONFIG['remote_file_root_directory']}/"+file);
    });
  });

app/views/workingplates/show.html.haml
-#
  Copyright (C) 2012 Juergen Helmers - All Rights Reserved
  You may not use, distribute and modify this code under any
  circumstance without the written permission of the author.

  Juergen Helmers <juergen.helmers@gmail.com>


%dl.show.dropshadow.raised
  %legend
    Workingplate
    = @workingplate.label
  %dt
    Uuid
  %dd
    Click on the link below and save the file in the root directory of the image tree derived from this workingplate.
    %p
    %span.bigger
      = link_to @workingplate.uuid, generate_uuid_file_workingplate_url(@workingplate.id)
    .clear
  %dt
    Masterplate
  %dd
    = link_to @workingplate.masterplate_label, @workingplate.masterplate
  -if @workingplate.description.present? || @workingplate.htd_file_info['Description'].present?
    %dt
      Description
    %dd
      -if @workingplate.htd_file_info['Description'].present?
        =@workingplate.htd_file_info['Description']
        %br
      =@workingplate.description

  %dt
    Image Status
  %dd
    -if @workingplate.imported
      Images have been processed.
    - elsif @workingplate.processing
      Images are currently being processed
    -else
      Images have not yet been processed.
  %dt
    Owner
  %dd
    = @workingplate.user_name
  - if @workingplate.remote_file_path.present? && @workingplate.imported?
    %dt
      Path to Image Files
    %dd
      =raw File.dirname(@workingplate.remote_file_path).gsub("/", "/<wbr>")

  - @wp = @workingplate.masterplate.workingplates.where("id != ?", @workingplate.id)
  - if @wp.present?
    %dt
      Other Workingplates
      %dd
        = @wp.map { |wp| link_to wp.label, workingplate_path(wp) }.join(", ").html_safe


%p
%p
  %div.outer
    %div#background.inner
      .workingplate.drop-shadow.raised
        -counter = 0
        - while counter < 96
          - w = @workingplate.workingwells.order('id ASC')[counter]
          - if w.present?
            %div{:class => "well, workingwell#{'pbs' if w.name == 'PBS'}#{'empty' if w.name == 'empty'}#{'control' if w.is_control?}", data: {animation: "true", placement: "top", trigger: "hover", html: "true", title: "#{w.name}",content: "#{popover(w)}"}}
              - if w.is_control?
                %div.small
                  = link_to w.name, w

              - elsif w.name == "PBS" || w.name == 'empty'
                = w.name
              -else
                = link_to w.name, w
          -else
            %div{:class => "well, workingwellpbs"}
          - counter += 1
    -if @workingplate.workingwells[13].analytical_results.heatmap_data.present?
      - @workingplate.workingwells[13].analytical_results.heatmap_data.each_with_index do |ar, index|
        %div.inner.ar{:id => "div_#{index}"}
          %div.workingplate
            -counter = 0
            - while counter < 96
              - w = @workingplate.workingwells[counter]
              - if w.analytical_results.heatmap_data[index].present?
                %div.well_ar{:style => "background-color: #{return_color_value(w.analytical_results.heatmap_data[index].value)}"}
                  -if w.is_control?
                    %div.small.shadow
                      = link_to w.name, w
                  -else
                    %div.shadow
                      = link_to w.name, w
              -else
                %div.well_ar{:style => "background: none"}
              - counter += 1

  -if @workingplate.workingwells[13].analytical_results.heatmap_data.present?
    %div.navigation
      %h3
        Navigation

      %form
        - @workingplate.workingwells[13].analytical_results.heatmap_data.each_with_index do |ar, index|
          %input{:type => 'checkbox', :name => 'div_select', :id => index}
          = ar.name
          %br

.clear
.form-actions.wp
  = link_to 'Back', workingplates_path, :class => 'btn btn-mini', :me => true
  - if current_user && @workingplate.user_id == current_user.id || current_user.admin?
    = link_to 'Edit', edit_workingplate_path(@workingplate), :class => 'btn btn-mini'
    = link_to 'Delete', workingplate_path(@workingplate), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger btn-mini'
    - if @workingplate.imported
      %button.btn.btn-mini.btn-diabled.import-right
        Processed
    - elsif @workingplate.processing
      = link_to 'Processing', '/resque', :class => 'btn btn-warning import-right', target: "_blank"
    -else
      = link_to 'Process Images', omeroimport_workingplate_path(@workingplate), :class => 'btn btn-mini btn-success import-right'

-if @workingplate.htd_file_info.present?
  - content_for :sidebar_title do
    HTD File Info
  - content_for :sidebar do
    %dl.side
      %dt
        X Wells:
      %dd
        =@workingplate.htd_file_info['XWells']

      %dt
        Y Wells:
      %dd
        =@workingplate.htd_file_info['YWells']

      %dt
        Wavelengths:
      %dd
        =@workingplate.htd_file_info['NWavelengths']
      %dt
        Wave Name 1
      %dd
        =@workingplate.htd_file_info['WaveName1']
      %dt
        Wave Name 2
      %dd
        =@workingplate.htd_file_info['WaveName2']
      - if @workingplate.htd_file_info['WaveName3'].present?
        %dt
          Wave Name 3
        %dd
          =@workingplate.htd_file_info['WaveName3']
      - if @workingplate.htd_file_info['WaveName3'].present?
        %dt
          Wave Name 4
      %dd
        =@workingplate.htd_file_info['WaveName4']

-if @workingplate.workingwells[13].analytical_results.heatmap_data.length > 0
  - content_for :sidebar_title do
    Analytical results
  - content_for :sidebar do
    %p
      Analytical results with possible values of "0" and "1" will be displayed as a heat map. The display of each value set can be
      turned on or off with the the check boxes on the right of the graphical plate representation. <br>
      %strong
        Note:
      The result set with the lowest checkbox checked is on top in the stack of result layers and will block any other result layer.