config/routes.rb
###
# Copyright (C) 2012 Juergen Helmers - All Rights Reserved
# You may not use, distribute and modify this code under any
# circumstance without the written permission of the author.
#
# Juergen Helmers <juergen.helmers@gmail.com>
###

Screeningandor::Application.routes.draw do

  resources :well_comparisons do
    member do
      get 'compare_with_control'
    end
  end

  get "send_images/show_file_by_send"

  resources :organisms

  resources :analytic_results

  resources :screen_settings

  devise_for :users

  resources :users, :except => [:new, :show] do
    member do
      get 'approve'
      get 'disable'
      get 'grant_admin'
      get 'deny_admin'
      get 'grant_receive_system_mail'
      get 'deny_receive_system_mail'
    end
  end

  resources :welcome, :only => :index
  
  resources :workingwells do
    member do
      get 'add_to_compare'
      get 'remove_from_compare'
    end
    collection do
      get 'clear_comparison_cart'
    end
  end

  match 'searches', to: 'workingwells#index', via: :get

  match 'jqueryfiletree/:id/content' => 'jqueryfiletree#content'#, :as => :content
  resources :jqueryfiletree do
    collection do
      post 'content'
    end
  end

  resources :workingplates do
    member do
      get 'omeroimport'
      post 'import'
      get 'generate_uuid_file'
    end
  end

  resources :masterwells, :only => [:new, :create, :show ]

  resources :masterplates

  resources :screens

  resources :well_names
  resources :well_uuids
  resources :metadata_record_values
  #resources :well_mature_sanger_ids
  #resources :well_precursor_accessions
  #resources :well_catalog_numbers
  #resources :well_mature_sequences


  authenticate :user do
    mount Resque::Server.new, :at => "/resque", :as => 'resque'
  end

  root :to => 'welcome#index'

end

app/views/shared/_navigation.html.haml
.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      %a.btn.btn-navbar{"data-target" => ".collapse", "data-toggle" => "collapse"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
        -if current_user
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
          -if current_user.admin?
            %span.icon-bar
            %span.icon-bar

      %a.brand{:href => "/"} Mhlangalab - Screening
      .nav-collapse
        %ul.nav
          - if current_user
            %li= link_to "Screens", screens_path(:me => "true")
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Plates & Wells
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Masterplates", masterplates_path(:me => "true")
                %li= link_to "Workingplates", workingplates_path(:me => "true")
                %li= link_to "Well Comparisons", well_comparisons_path(:me => "true")

            %li= link_to "Search", searches_path
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Processing Queue
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Monitoring", resque_url, :target => "_blank"
                %li.divider
                %li= link_to "Number of workers: #{Resque.workers.length}", "#", disabled: true
                -if Resque.working.length > 0
                  %li= link_to "Jobs working: #{Resque.working.length}", "#"
                  %li= link_to "Jobs pending: #{Resque.size('ome_rewrite') || 0}", "#"
                %li= link_to raw("Jobs failed: #{failed_jobs}"), "#"
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                = current_user.username
                %b.caret
              %ul.dropdown-menu
                %li= link_to "User Profile", edit_user_path(current_user)
                %li= link_to "Logout", destroy_user_session_path, :method => :delete
            - if current_user.admin?
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  Admin
                  %b.caret
                %ul.dropdown-menu
                  %li= link_to "Users", users_path
                  %li= link_to "Organisms", organisms_path
          -else
            %li= link_to "Sign In", new_user_session_path