config/routes.rb
###
# Copyright (C) 2012 Juergen Helmers - All Rights Reserved
# You may not use, distribute and modify this code under any
# circumstance without the written permission of the author.
#
# Juergen Helmers <juergen.helmers@gmail.com>
###

Screeningandor::Application.routes.draw do

  resources :well_comparisons do
    member do
      get 'compare_with_control'
    end
  end

  get "send_images/show_file_by_send"

  resources :organisms

  resources :analytic_results

  resources :screen_settings

  devise_for :users

  resources :users, :except => [:new, :show] do
    member do
      get 'approve'
      get 'disable'
      get 'grant_admin'
      get 'deny_admin'
      get 'grant_receive_system_mail'
      get 'deny_receive_system_mail'
    end
  end

  resources :welcome, :only => :index
  
  resources :workingwells do
    member do
      get 'add_to_compare'
      get 'remove_from_compare'
    end
    collection do
      get 'clear_comparison_cart'
    end
  end

  match 'searches', to: 'workingwells#index', via: :get

  match 'jqueryfiletree/:id/content' => 'jqueryfiletree#content'#, :as => :content
  resources :jqueryfiletree do
    collection do
      post 'content'
    end
  end

  resources :workingplates do
    member do
      get 'omeroimport'
      post 'import'
      get 'generate_uuid_file'
    end
  end

  resources :masterwells, :only => [:new, :create, :show ]

  resources :masterplates

  resources :screens

  resources :well_names
  resources :well_uuids
  resources :metadata_record_values
  #resources :well_mature_sanger_ids
  #resources :well_precursor_accessions
  #resources :well_catalog_numbers
  #resources :well_mature_sequences


  authenticate :user do
    mount Resque::Server.new, :at => "/resque", :as => 'resque'
  end

  root :to => 'welcome#index'

end

app/models/workingwell.rb
###
# Copyright (C) 2012 Juergen Helmers - All Rights Reserved
# You may not use, distribute and modify this code under any
# circumstance without the written permission of the author.
#
# Juergen Helmers <juergen.helmers@gmail.com>
###

class Workingwell < ActiveRecord::Base

  belongs_to :workingplate
  belongs_to :user

  has_many :metadata_records, as: :metadatarecordable, :dependent => :destroy
  has_many :analytical_results, :dependent => :destroy

  has_many :comparizations
  has_many :workingwells, through: :comparizations

  validates :name, presence: true
  validates :uuid, presence: true

  #scope :with_name_and_value_range,lambda {|name, low, high| joins(:analytical_results).where(:analytical_results => {:name => name, :value => low..high}) }
  #scope :with_name_and_value_range,lambda {|name, low, high|
  #joins(:analytical_results).where(['analytical_results.name = ?', name]).where(['analytical_results.value >= ?', low]).where(['analytical_results.value <= ?', high])}
  default_scope order('id ASC')

  scope :with_name_and_value_range,lambda {|name, low, high|
    joins(:analytical_results).where(['analytical_results.name = ?', name]).with_low(low).with_high(high) }
  scope :with_name,lambda {|name|
    joins(:analytical_results).where(['analytical_results.name = ?', name])}
  scope :with_low,lambda {|low|
    joins(:analytical_results).where(['analytical_results.value >= ?', low]) unless low.blank?}
  scope :with_high,lambda {|high|
    joins(:analytical_results).where(['analytical_results.value <= ?', high]) unless high.blank?}

  search_methods :with_name_and_value_range,
    :splat_param => true, :type => [:string, :string, :string]

  def set_uuid
    self.uuid = UUIDTools::UUID.timestamp_create().to_s
  end

  def self.to_csv(options = {col_sep: ";"})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |well|
        csv << well.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/workingwells_controller.rb
###
# Copyright (C) 2012 Juergen Helmers - All Rights Reserved
# You may not use, distribute and modify this code under any
# circumstance without the written permission of the author.
#
# Juergen Helmers <juergen.helmers@gmail.com>
###

class WorkingwellsController < ApplicationController
  # GET /workingwells
  # GET /workingwells.json
  # require 'csv'

  before_filter :authenticate_user!

  def index
    session[:compare] = {} unless session[:compare].present?
    @screens = Screen.order("name ASC")#.collect{|x| x.name}
    @users = User.where("username != ?", "admin").order("username ASC")#collect{|x| x.username}
    @analytical_results = AnalyticalResult.select(:name).uniq if AnalyticalResult.all.size > 0
    new = {}                                        # instantiate a new has to hold extra values
    if params[:search].present?
      params[:search].each do |key, value|            # loop over the params[:search] hash
        if key.include? "with_name_and_value_range"   # check if the key contains "with_name_and_value_range"
          new[key] = value                            # if yes add the new key-value pair to the new hash
          params[:search].delete(key)                 # remove the key-value pair from the params[:search] hash
        end
      end
    else
      params[:search] = {}
    end
    @search = Workingwell.includes(:analytical_results).where("workingwells.name != ? AND workingwells.name != ?", "PBS", "empty")
    if new.length > 0
      new_a = new.to_a.each_slice(3).to_a             # convert new has into an 2d array
      count = 0
      while count < new_a.length
        if new_a[count][1][1] != ""
          @search = @search.joins(:analytical_results).where("analytical_results.name = ? AND analytical_results.value >= ?", "#{new_a[count][0][1]}", "#{new_a[count][1][1].to_f}")
        end
        if new_a[count][2][1] != ""
          @search = @search.joins(:analytical_results).where("analytical_results.name = ? AND analytical_results.value <= ?", "#{new_a[count][0][1]}", "#{new_a[count][2][1].to_f}")
        end
        count += 1
      end
    end
    @search = @search.search(params[:search])
    if new.length > 0
      params[:search] = params[:search].merge(new)
    end


    @workingwells = @search.paginate(:page => params[:page])
    # @ww_csv = @search.all

    respond_to do |format|
      format.html
      # format.csv { send_data @ww_csv.to_csv }
    end

  end

  # GET /workingwells/1
  # GET /workingwells/1.json
  def show
    @workingwell = Workingwell.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @workingwell }
    end
  end

  # GET /workingwells/new
  # GET /workingwells/new.json
  def new
    @workingwell = Workingwell.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @workingwell }
    end
  end

  # GET /workingwells/1/edit
  def edit
    @workingwell = Workingwell.find(params[:id])
  end

  # POST /workingwells
  # POST /workingwells.json
  def create
    @workingwell = Workingwell.new(params[:workingwell])
    @workingwell.update_attributes(:user_id => current_user.id)

    respond_to do |format|
      if @workingwell.save
        format.html { redirect_to @workingwell, notice: 'Workingwell was successfully created.' }
        format.json { render json: @workingwell, status: :created, location: @workingwell }
      else
        format.html { render action: "new" }
        format.json { render json: @workingwell.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /workingwells/1
  # PUT /workingwells/1.json
  def update
    @workingwell = Workingwell.find(params[:id])

    respond_to do |format|
      if current_user.id == @workingwell.user_id && @workingwell.is_control?
        if @workingwell.update_attributes(params[:workingwell])
          format.html { redirect_to workingplate_path(@workingwell.workingplate.id), notice: 'Workingwell was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @workingwell.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to workingplate_path(@workingwell.workingplate.id), notice: 'Workingwell record does not belong to you or is no control.' }
      end

    end
  end


  def add_to_compare
    @workingwell = Workingwell.find(params[:id])
    session[:compare] = {} unless session[:compare].present?
    session[:compare].merge!(:"#{params[:id]}" => params[:id])
    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
    
  end

  def remove_from_compare
    @workingwell = Workingwell.find(params[:id])
    session[:compare] = {} unless session[:compare].present?
    session[:compare].delete(:"#{params[:id]}")
    respond_to do |format|
      format.html { redirect_to :back}
      format.js
    end

    
  end

  def clear_comparison_cart
    @workingwell_ids = format_session_compare(session[:compare])
    session[:compare] = {}
    respond_to do |format|
      format.html { redirect_to :back, notice: "The Comparisons have been cleared." }
      format.js
    end

  end

  protected

  def format_session_compare(session)
    string = []
    session.each do |k,id|
      string << "{ workingwell_id: #{id}}"
    end
    return string.join(",")
  end

end

app/helpers/workingwells_helper.rb
###
# Copyright (C) 2012 Juergen Helmers - All Rights Reserved
# You may not use, distribute and modify this code under any
# circumstance without the written permission of the author.
#
# Juergen Helmers <juergen.helmers@gmail.com>
###

module WorkingwellsHelper
  def popover(well)
    if well.montage_url.present?
      url = image_tag url_for(:controller => 'send_images', :action => 'show_file_by_send', :filepath => "#{APP_CONFIG['remote_file_root_directory']}#{well.montage_url}"), :class => "popover_image"
      popover = "#{url} </br>"
    else
    popover = ""
    end
    if well.is_control?
      return popover
    else
      well.metadata_records.order("position ASC").each do |mr|
        popover << "<strong>#{mr.name}:</strong> #{mr.value} </br>" unless mr.name == ""
      end

      return popover.html_safe
    end
  end

  def popover_link(well)
    if well.montage_url.present?
      url = image_tag url_for(:controller => 'send_images', :action => 'show_file_by_send', :filepath => "#{APP_CONFIG['remote_file_root_directory']}#{well.montage_url}"), :class => "popover_image"
      popover = "#{url} </br>"
    else
      popover = ""
    end
    if well.analytical_results.where(name: "Euclidean Distance").present?
      popover << "Euclidean Distance: #{well.analytical_results.where(name: "Euclidean Distance").first.value.to_f.round(4)}"
    else
      popover << ""
    end

    return popover.html_safe

  end


  def metadata_record(well,position)
    mr =  well.metadata_records.order("position ASC")[position] || []
    if mr.present?
      "#{mr.value} <small>(#{mr.name})</small>"
    elsif well.is_control?
      well.name
    else
      "<center>-</center>"
    end
  end

  def euclidean_distance(well)
    ed = "-"
    if well.analytical_results.present? && well.analytical_results.where(name: "Euclidean Distance").present?
      ed = well.analytical_results.where(name: "Euclidean Distance").first.value.to_f.round(4).to_s
    end
    return "<center>#{ed}</center>"
  end

  def list_compare_wells(id)
    well = Workingwell.find(id)
    string = "<tr class='row_#{well.id}'>"
    if well.is_control?
      string << "<td colspan='2'>#{well.name}</td>"
    else
      string << "<td>#{well.name}</td>"
      string << "<td>#{well.metadata_records.order("position ASC").first.value if well.metadata_records.present?}</td>"
    end
    string << "<td class='center'>#{link_to 'x', remove_from_compare_workingwell_path(id), remote: true, class: 'btn btn-mini btn-danger'}</td>"
    string << "</tr>"
    return string  
  end

end

app/views/workingwells/_analytical_results.html.haml
-#
  Copyright (C) 2012 Juergen Helmers - All Rights Reserved
  You may not use, distribute and modify this code under any
  circumstance without the written permission of the author.

  Juergen Helmers <juergen.helmers@gmail.com>


%dl.show
  %h3.analytical_results
    Analytical Results
  - @workingwell.analytical_results.each do |ar|
    %dt
      = ar.name
    %dd
      - unless ar.value.blank?
        %div.ar_square{:style => "background: #{return_color_value(ar.value)}"}
        %p.ar_value
          = ar.value
      -else
        = "No result yet..."

app/views/workingwells/_ar.html.haml
%dt
  = ar.name
%dd
  - unless ar.value.blank?
    %div.ar_square{:style => "background: #{return_color_value(ar.value)}"}
    %p.ar_value
      = ar.value
  -else
    = "No result yet..."

app/views/workingwells/_form.html.haml
-#
  Copyright (C) 2012 Juergen Helmers - All Rights Reserved
  You may not use, distribute and modify this code under any
  circumstance without the written permission of the author.

  Juergen Helmers <juergen.helmers@gmail.com>


= form_for @workingwell, :html => { :class => 'form-horizontal' } do |f|
  %fieldset
    %legend
      = controller.action_name.capitalize
      Workingwell
    -if @workingwell.montage_url.present?
      .control-group
        = f.label "File Names", :class => 'control-label'
        .controls
          = "#{APP_CONFIG['remote_file_root_directory']}/#{@workingwell.montage_url.split('/')[-1].gsub("_w1.png", "").gsub("_w2.png", "")}_s(1,2,3,4)_w(1,2).TIF"
      .control-group
        = f.label "Montage", :class => 'control-label'
        .controls
          = image_tag url_for(:controller => 'workingwells', :action => 'show_file_by_send', :filepath => "#{APP_CONFIG['remote_file_root_directory']}#{@workingwell.montage_url}"), :class => "montage_image"
          -#= image_tag url_for(:controller => 'workingwells', :action => 'show_file_by_send', :filepath => "#{@workingwell.montage_url}"), :class => "montage_image"
    .control-group
      = f.label "workingplate", :class => 'control-label'
      .controls
        = f.text_field :workingplate_id, :class => 'number_field', :value => @workingwell.workingplate.label, :disabled => true
    .control-group
      = f.label :name, :class => 'control-label'
      .controls
        = f.text_field :name, :class => 'text_field'
    - if @workingwell.is_control?
      .control-group
        = f.label :substance, :class => 'control-label'
        .controls
          = f.text_field :substance, :class => 'text_field'
      .control-group
        = f.label :concentration, :class => 'control-label'
        .controls
          = f.text_field :concentration, :class => 'text_field'
      .control-group
        = f.label :buffer, :class => 'control-label'
        .controls
          = f.text_field :buffer, :class => 'text_field'
    .clear
    - unless @workingwell.analytical_results.length == 0
      = render 'analytical_results'
      .clear

    .form-actions
      -if @workingwell.user_id == current_user.id
        = f.submit nil, :class => 'btn btn-mini btn-primary'
        = link_to 'Cancel', workingplate_path(@workingwell.workingplate.id), :class => 'btn btn-mini', :me => true
      -else
        = link_to 'Back', workingplate_path(@workingwell.workingplate.id), :class => 'btn btn-mini', :me => true
        The displayed record does not belong to you.

app/views/workingwells/add_to_compare.js.erb
//change the button color to red and the url to remove from
$("a.well_<%= @workingwell.id %>").removeClass( "btn-success" ).addClass( "btn-danger");
var addhref = $("a.well_<%= @workingwell.id %>").attr('href');
$("a.well_<%= @workingwell.id %>").attr('data-addhref', addhref);
$("a.well_<%= @workingwell.id %>").attr("href", "<%= remove_from_compare_workingwell_path(@workingwell) %>");
// show the table, the action links and hide the empty card div
$('#user_nav.raised.well_comparison table').show();
$('#compare_actions_links').show();
$('#empty_cart').hide();
//add the new line using the helper
$('#user_nav.raised.well_comparison table tbody').append('<%= j list_compare_wells(@workingwell.id).html_safe %>');

app/views/workingwells/clear_comparison_cart.js.erb
$('#user_nav.raised.well_comparison table').hide();
$('#compare_actions_links').hide();
$('#empty_cart').show();
$('table#search a.btn-danger').each( function( index, element ){
    $( this ).attr( 'href', $( this ).attr('data-addhref')).removeClass( "btn-danger" ).addClass( "btn-success");
});

app/views/workingwells/edit.html.haml
-#
  Copyright (C) 2012 Juergen Helmers - All Rights Reserved
  You may not use, distribute and modify this code under any
  circumstance without the written permission of the author.

  Juergen Helmers <juergen.helmers@gmail.com>


= render :partial => 'form'

app/views/workingwells/index.html.haml
-#
  Copyright (C) 2012 Juergen Helmers - All Rights Reserved
  You may not use, distribute and modify this code under any
  circumstance without the written permission of the author.

  Juergen Helmers <juergen.helmers@gmail.com>



= form_for @search, :html => { :class => 'well form-horizontal' } do |f|
  %fieldset
    %legend
      Search Workingwells
    %dl.search
      %dt
        = f.label :workingplate_masterplate_screen_user_username_contains, "User"
      %dd
        = f.collection_select :workingplate_masterplate_screen_user_username_contains, @users, :username, :fullname, {:include_blank => 'Select a user...'}
        / 
      %dt.screen
        = f.label :workingplate_masterplate_screen_name_contains, "Screen"
      %dd.screen
        //= f.select :workingplate_masterplate_screen_name_contains, @screens, {:include_blank => 'Select a screen...'}
        = f.grouped_collection_select :workingplate_masterplate_screen_name_contains, User.order(:firstname), :screens, :fullname, :name, :name,  {:include_blank => 'Select a screen...'}
        / , { selected: current_user.screens.last }
      %dt
        = f.label :workingplate_label_contains, "Workingplate label"
      %dd
        = f.text_field :workingplate_label_contains, data: {autocomplete_source: workingplates_path}
        .clear
      %dt
        = f.label :name_contains, "Well name"
      %dd
        = f.text_field :name_contains, data: {autocomplete_source: well_names_path}
        .clear
      %dt
        = f.label :uuid_contains, "Well UUID"
      %dd 
        = f.text_field :uuid_contains, data: {autocomplete_source: well_uuids_path}
        .clear
      %dt
        = f.label :metadata_records_value_contains, "Metadata"
      %dd
        = f.text_field :metadata_records_value_contains, data: {autocomplete_source: metadata_record_values_path}
        .clear

    .clear


    -if @analytical_results.present?
      %h4.search
        Analytical Results
      %dl.search
        - count = 1
        -@analytical_results.each do |result|
          %dt
            = f.label :with_name_and_value_range, result.name
          %dd
            = f.multiparameter_field :with_name_and_value_range,
            {:field_type => :hidden_field, :value => "#{result.name}", :id => "search_with_name_and_value_range(#{count})", :name => "search[with_name_and_value_range(#{count})]"},
            {:field_type => :text_field, :placeholder => "from", :class => "small_field",:id => "search_with_name_and_value_range(#{count + 1})",:value => params[:search]["with_name_and_value_range(#{count +1})"],:name => "search[with_name_and_value_range(#{count + 1})]"},
            {:field_type => :text_field, :placeholder => "to", :class => "small_field",:value => params[:search]["with_name_and_value_range(#{count +2})"],:id => "search_with_name_and_value_range(#{count + 2})", :name => "search[with_name_and_value_range(#{count + 2})]"}
            - count += 3

    .clear
    .form-actions.left
      = f.submit "Search", :class => 'btn btn-mini btn-success'
      = link_to 'Cancel', workingplates_path, :class => 'btn btn-mini btn-danger', :me => true


-if @workingwells.length > 0
  .top_header.right
    %p.strong
      = @workingwells.total_entries
      -if params[:search].length > 0
        wells have been found
      -else
        wells are on record

  %table#search.table.table-striped
    %thead
      %tr
        %th Meta Data
        %th Meta Data
        %th Plate Name
        %th Euclidean Distance
        %th.action


    %tbody
      - @workingwells.each do |well|
        %tr{class: "well_#{well.id}"}
          %td= link_to metadata_record(well,0).html_safe, well, target: "_blank", class: "popover_link", data: {animation: "true", placement: "top", trigger: "hover", html: "true", title: "#{well.name}",content: "#{popover_link(well)}"}
          %td= link_to metadata_record(well,1).html_safe, well, target: "_blank", class: "popover_link", data: {animation: "true", placement: "top", trigger: "hover", html: "true", title: "#{well.name}",content: "#{popover_link(well)}"}
          %td= link_to well.workingplate.label, workingplate_path(well.workingplate_id), target: "_blank"
          %td
            %span{class: 'popover_link', data: {animation: "true", placement: "top", trigger: "hover", html: "true", title: "#{well.name}",content: "#{popover_link(well)}"}}
              = euclidean_distance(well).html_safe
          -if session[:compare].has_value?("#{well.id}")
            %td= link_to 'Compare', remove_from_compare_workingwell_path(well), remote: true, class: "btn btn-mini btn-danger popover_link well_#{well.id}", data: {animation: "true", placement: "right", trigger: "hover", html: "true", title: "#{well.name}",content: "#{popover_link(well)}"}
          -else
            %td= link_to 'Compare', add_to_compare_workingwell_path(well), remote: true, class: "btn btn-mini btn-success popover_link well_#{well.id}", data: {animation: "true", placement: "right", trigger: "hover", html: "true", title: "#{well.name}",content: "#{popover_link(well)}"}
  = will_paginate(@workingwells, :class => 'apple_pagination')
-else
  %p
    %br
  %div.no_record
    %p
      There are no wells on record matching your query.

- content_for :sidebar do
  #user_nav.raised.well_comparison
    %h4 Well Comparison
    #empty_cart
      %p Currently no wells present.
    %table.table.table-striped
      %thead
        %th Well
        %th name
        %th
      %tbody
        -if session[:compare].present?
          - session[:compare].each do |key,id|
            = list_compare_wells(id).html_safe

    #compare_actions_links
      =link_to "Clear all", clear_comparison_cart_workingwells_path, data: {remote: true, confirm: "Are you sure?"} ,class: "btn btn-mini btn-danger"
      =link_to "View Comparison", new_well_comparison_path, class: "btn btn-mini btn-success pull-right"
  %h3 Searching Screening Results
  %ul
    %li use the advanced search form to identify relevant wells
    %li in the top part of the form you can search for well, plate, screen, or user related fields
    %li all text fields have an auto-search function suggesting matching records depending on your input.

  %h5 Analytical Results
  %ul
    %li analytical scripts (e.g. matlab) will be able to attach different results to analyzed wells
    %li the results will be displayed in the well show view as heatmaps
    %li in case of existing analytical results from matlab you can
    %ul
      %li search for a well by specifying a minimum value
      %li search for a well by specifying a maximum value
      %li search for a well by specifying a minimum and maximum value
      %li the search will return wells that meet all your search requirements
      %li click on the well name to visually inspect the information stored for the well of interest

app/views/workingwells/remove_from_compare.js.erb
// hide the table row from the comparison cart table
$("tr.row_<%= @workingwell.id %>").remove();
$("a.well_<%= @workingwell.id %>").removeClass( "btn-danger" ).addClass( "btn-success" ).attr("href", "<%= add_to_compare_workingwell_path(@workingwell) %>")

//determine the number of remaining comparison cart table rows
var count = $('#user_nav.raised.well_comparison table tr').length;
// if the number is smaller or equal to 1 (table header is a row), remove the cart
if ( count <= 1 )
  {
    $('#user_nav.raised.well_comparison table').hide();
    $('#compare_actions_links').hide();
    $('#empty_cart').show();
  }
// handle the call to this action from the well_comparison view
// remove the well_container using a fade out animation
$('.well_<%= @workingwell.id %>').fadeOut(1000, function() {
    $(this).remove();
    // get the number of remaining well_containers
    var well_container_count = $('.well_container').length;
    // if the number of well_container is zero, remove the save link and show the notice
    if ( well_container_count <= 0 )
      {
        $('input.save').remove();
        $('.no_well_notice').append( "<p>You have to have at least one well in a comparison to save it.</p>" );
      }
    });

app/views/workingwells/show.html.haml
-#
  Copyright (C) 2012 Juergen Helmers - All Rights Reserved
  You may not use, distribute and modify this code under any
  circumstance without the written permission of the author.

  Juergen Helmers <juergen.helmers@gmail.com>


%dl.show.dropshadow.raised
  %legend
    Workingwell
    = @workingwell.name
    on
    = @workingwell.workingplate.label

  -if @workingwell.montage_url.present?
    %dt
      File names
    %dd
      = "#{APP_CONFIG['remote_file_root_directory']}/#{@workingwell.montage_url.split('/')[-1].gsub("_w1.png", "").gsub("_w2.png", "")}_s(1,2,3,4)_w(1,2).TIF"
    %dt
      Montage
    %dd
      = image_tag url_for(:controller => 'send_images', :action => 'show_file_by_send', :filepath => "#{APP_CONFIG['remote_file_root_directory']}#{@workingwell.montage_url}"), :class => "montage_image"

  -unless @workingwell.is_control?
    -if @workingwell.metadata_records.present?
      - @workingwell.metadata_records.order("name ASC").each do |mr|
        - unless mr.name == ""
          %dt
            = mr.name
          %dd
            = mr.value

  %dt
  %dd
    %p
      %br
  %dt
    Workingplate
  %dd
    = link_to @workingwell.workingplate.label, @workingwell.workingplate

  %dt
    Owner
  %dd
    = @workingwell.user.username

  %dt
    Uuid
  %dd
    = @workingwell.uuid

  -if @workingwell.workingplate.htd_file_info.present?
    %dt
      Wavelengths
    %dd
      = @workingwell.workingplate.htd_file_info['NWavelengths']
    %dt
      Wave Name 1
    %dd
      =@workingwell.workingplate.htd_file_info['WaveName1']
    %dt
      Wave Name 2
    %dd
      =@workingwell.workingplate.htd_file_info['WaveName2']
    - if @workingwell.workingplate.htd_file_info['WaveName3'].present?
      %dt
        Wave Name 3
      %dd
        =@workingwell.workingplate.htd_file_info['WaveName3']
    - if @workingwell.workingplate.htd_file_info['WaveName4'].present?
      %dt
        Wave Name 4
      %dd
        =@workingwell.workingplate.htd_file_info['WaveName4']

  - if @workingwell.is_control?

    %dt
      Substance
    %dd
      = @workingwell.substance

    %dt
      Concentration
    %dd
      = @workingwell.concentration

    %dt
      Buffer
    %dd
      = @workingwell.buffer
    .clear

  - unless @workingwell.analytical_results.length == 0
    %dt
    %dd
    %h4.left
      Analytical Results

    - @workingwell.analytical_results.heatmap_data.each do |ar|
      %dt
        = ar.name
      %dd
        - unless ar.value.blank?
          %div.ar_square{:style => "background: #{return_color_value(ar.value)}"}
          %p.ar_value
            = ar.value
        -else
          = "no results have been recorded yet"
    - @workingwell.analytical_results.not_heatmap_data.each do |ar|
      %dt
        = ar.name.titleize
      %dd
        = ar.value.present? ? "#{ar.value}":"no results have been recorded yet"
.clear
.form-actions
  = link_to 'Back', url_for(:back) , :class => 'btn btn-mini', :me => true
  - if @workingwell.is_control? && @workingwell.user_id == current_user.id
    = link_to 'Edit', edit_workingwell_path(@workingwell), :class => 'btn btn-mini'