config/routes.rb
###
# Copyright (C) 2012 Juergen Helmers - All Rights Reserved
# You may not use, distribute and modify this code under any
# circumstance without the written permission of the author.
#
# Juergen Helmers <juergen.helmers@gmail.com>
###

Screeningandor::Application.routes.draw do

  resources :well_comparisons do
    member do
      get 'compare_with_control'
    end
  end

  get "send_images/show_file_by_send"

  resources :organisms

  resources :analytic_results

  resources :screen_settings

  devise_for :users

  resources :users, :except => [:new, :show] do
    member do
      get 'approve'
      get 'disable'
      get 'grant_admin'
      get 'deny_admin'
      get 'grant_receive_system_mail'
      get 'deny_receive_system_mail'
    end
  end

  resources :welcome, :only => :index
  
  resources :workingwells do
    member do
      get 'add_to_compare'
      get 'remove_from_compare'
    end
    collection do
      get 'clear_comparison_cart'
    end
  end

  match 'searches', to: 'workingwells#index', via: :get

  match 'jqueryfiletree/:id/content' => 'jqueryfiletree#content'#, :as => :content
  resources :jqueryfiletree do
    collection do
      post 'content'
    end
  end

  resources :workingplates do
    member do
      get 'omeroimport'
      post 'import'
      get 'generate_uuid_file'
    end
  end

  resources :masterwells, :only => [:new, :create, :show ]

  resources :masterplates

  resources :screens

  resources :well_names
  resources :well_uuids
  resources :metadata_record_values
  #resources :well_mature_sanger_ids
  #resources :well_precursor_accessions
  #resources :well_catalog_numbers
  #resources :well_mature_sequences


  authenticate :user do
    mount Resque::Server.new, :at => "/resque", :as => 'resque'
  end

  root :to => 'welcome#index'

end

app/models/well_comparison.rb
###
# Copyright (c) 2014 Juergen Helmers - All Rights Reserved
# You may not use, distribute and modify this code under any
# circumstance without the written permission of the author.
#
# Juergen Helmers <juergen.helmers@gmail.com>
###

class WellComparison < ActiveRecord::Base
  attr_accessible :description, :user_id, :uuid

  belongs_to :user
  has_many :comparizations
  has_many :workingwells, through: :comparizations

  validates :user_id, presence: true



  before_create :set_uuid



private
  def set_uuid
   self.uuid = UUIDTools::UUID.timestamp_create().to_s
  end

end

app/controllers/well_comparisons_controller.rb
###
# Copyright (c) 2014 Juergen Helmers - All Rights Reserved
# You may not use, distribute and modify this code under any
# circumstance without the written permission of the author.
#
# Juergen Helmers <juergen.helmers@gmail.com>
###

class WellComparisonsController < ApplicationController
  layout "full_with"
  before_filter :authenticate_user!

  # GET /well_comparisons
  # GET /well_comparisons.json
  def index
    if params[:me] == "true"
      @well_comparisons = WellComparison.where(:user_id => current_user.id)
    else
      @well_comparisons = WellComparison.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @well_comparisons }
    end
  end

  # GET /well_comparisons/1
  # GET /well_comparisons/1.json
  def show
    @well_comparison = WellComparison.find(params[:id])
    # render layout: "full_with"
  end

  # GET /well_comparisons/new
  # GET /well_comparisons/new.json
  def new
    @well_comparison = WellComparison.new
    # render layout: "full_with"
    # respond_to do |format|
    #   format.html # new.html.erb
    #   format.json { render json: @well_comparison }
    # end
  end

  # GET /well_comparisons/1/edit
  def edit
    @well_comparison = WellComparison.find(params[:id])
  end

  # POST /well_comparisons
  # POST /well_comparisons.json
  def create
    if session[:compare].length > 0
      @well_comparison = WellComparison.new(params[:well_comparison])
      @well_comparison.update_attributes(user_id: current_user.id)
      @well_comparison.workingwell_ids = session[:compare].values

      respond_to do |format|
        if @well_comparison.save
          session[:compare] = {}
          format.html { redirect_to @well_comparison, notice: 'Well Comparison was successfully saved.' }
          format.json { render json: @well_comparison, status: :created, location: @well_comparison }
        else
          format.html { render action: "new" }
          format.json { render json: @well_comparison.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to new_well_comparison_path, notice: 'You have to include at least one well in a comparison.'
    end

  end

  # PUT /well_comparisons/1
  # PUT /well_comparisons/1.json
  def update
    @well_comparison = WellComparison.find(params[:id])

    respond_to do |format|
      if @well_comparison.user_id == current_user.id || current_user.admin?
        if @well_comparison.update_attributes(params[:well_comparison])
          format.html { redirect_to @well_comparison, notice: 'Well comparison was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @well_comparison.errors, status: :unprocessable_entity }
        end
      else
        redirect_to @well_comparison, notice: 'This Well Comparison does nto belong to you.'
      end

    end
  end

  # DELETE /well_comparisons/1
  # DELETE /well_comparisons/1.json
  def destroy
    @well_comparison = WellComparison.find(params[:id])
    if @well_comparison.user_id == current_user.id || current_user.admin?
      @well_comparison.destroy

      respond_to do |format|
        format.html { redirect_to well_comparisons_url }
        format.json { head :no_content }
      end
    else
      redirect_to @well_comparison, notice: 'This Well Comparison does not belong to you.'
    end
  end

  def compare_with_control
    @workingwell = Workingwell.find(params[:id])
    @control_wells = @workingwell.workingplate.workingwells.where(is_control: true ).limit(10)

  end

end

app/helpers/well_comparisons_helper.rb
###
# Copyright (c) 2014 Juergen Helmers - All Rights Reserved
# You may not use, distribute and modify this code under any
# circumstance without the written permission of the author.
#
# Juergen Helmers <juergen.helmers@gmail.com>
###

module WellComparisonsHelper

    def table_euclidean_distance(well)
      if well.analytical_results.where(name: "Euclidean Distance").exists?
        return "<tr><td class='col_one'>Eucl. Distance</td><td>#{well.analytical_results.where(name: "Euclidean Distance").first.value.to_f.round(4).to_s}</td></tr>"
      else
        return "<tr><td>Euclidean Distance</td><td>not calculated</td></tr>"
      end
    end

    def comparison_metadata_records(well)
      return "<tr><td class='col_one'>#{well.metadata_records.order("position ASC").first.name}</td><td>#{well.metadata_records.order("position ASC").first.value}</td></tr>"
    end

    def comparison_control(well)
      return "<tr><td class='col_one'>Control</td><td>#{well.name}</td></tr>"
    end


    def popover_comparison(well_comparison)
      well_ids = well_comparison.workingwell_ids
      if well_ids.length > 0
        string = "<table>"
        Workingwell.find(well_ids).each do |well|
          string << "<tr>"
          if well.is_control?
            string << "<td colspan='2'>#{well.name}</td>"
          else
            string << "<td>#{well.name}</td>"
            string << "<td>#{well.metadata_records.order("position ASC").first.value if well.metadata_records.present?}</td>"
          end
          string << "</tr>"
        end
        string << "</table>"
      else
        string = "<p>No wells found.</p>"
      end
      return string
    end

end

app/views/well_comparisons/_form.html.haml
-#
  Copyright (C) 2014 Juergen Helmers - All Rights Reserved
  You may not use, distribute and modify this code under any
  circumstance without the written permission of the author.

  Juergen Helmers <juergen.helmers@gmail.com>


= form_for @well_comparison, :html => { :class => 'well form-horizontal' } do |f|
  - if @well_comparison.errors.any?
    #error_explanation
      %h2= "#{pluralize(@well_comparison.errors.count, "error")} prohibited this well_comparison from being saved:"
      %ul
        - @well_comparison.errors.full_messages.each do |msg|
          %li= msg
  %fieldset
    %legend
      = controller.action_name.capitalize
      Well Comparison
    .control-group
      = f.label :description, :class => 'control-label'
      .controls
        = f.text_area :description, rows: '1', :class => 'span8', :placeholder => "Well Comparison Description"
        %span.help-inline
          To identify comparisons later, best to add a good description!


    -if session[:compare].present?
      - session[:compare].each_with_index do |(k,id),index|
        -well = Workingwell.find(id)
        -if well.montage_url.present?
          .well_container.comparison{ class: "well_#{well.id}"}

            =image_tag url_for(:controller => 'send_images', :action => 'show_file_by_send', :filepath => "#{APP_CONFIG['remote_file_root_directory']}#{well.montage_url}"), :class => "montage_image sq250"
            %p.ed
              %table
                %tbody
                  = table_euclidean_distance(well).html_safe if well.analytical_results.where(name: "Euclidean Distance").exists?
                  = comparison_metadata_records(well).html_safe if well.metadata_records.present?
                  = comparison_control(well).html_safe if well.is_control?
                  .clear
                  %tr
                    %td= link_to 'x', remove_from_compare_workingwell_path(id), remote: true, class: 'btn btn-mini btn-danger overlay'
                    %td= link_to 'view with controls', compare_with_control_well_comparison_path(well), class: "btn btn-mini", target: "_blank"

  .form-actions
    -if session[:compare].length == 0
      .no_well_notice
        %p
          You have to have at least one well in a comparison to save it.
      = link_to 'Back', searches_path, class: 'btn btn-mini btn-default'
    -else
      .no_well_notice
      = link_to 'Back', searches_path, class: 'btn btn-mini btn-default'
      = f.submit 'Save Comparison', class: 'btn btn-mini btn-success save'

app/views/well_comparisons/compare_with_control.html.haml
-#
  Copyright (C) 2012 Juergen Helmers - All Rights Reserved
  You may not use, distribute and modify this code under any
  circumstance without the written permission of the author.

  Juergen Helmers <juergen.helmers@gmail.com>


%h1 Well Control - Comparison
%legend
  Workingwell
  = @workingwell.name
  on
  = @workingwell.workingplate.label
  = link_to 'Close', "javascript:closeWindow();", class: 'btn btn-mini btn-danger'
#comparison_grid
  -if @workingwell.montage_url.present?
    .well_container
      =image_tag url_for(:controller => 'send_images', :action => 'show_file_by_send', :filepath => "#{APP_CONFIG['remote_file_root_directory']}#{@workingwell.montage_url}"), :class => "montage_image sq250 workingwell"
      %p.ed
        %table
          %tbody
            = table_euclidean_distance(@workingwell).html_safe if @workingwell.analytical_results.where(name: "Euclidean Distance").exists?
            = comparison_metadata_records(@workingwell).html_safe if @workingwell.metadata_records.present?
            = comparison_control(@workingwell).html_safe if @workingwell.is_control?

  - @control_wells.each do |well|
    .well_container
      =image_tag url_for(:controller => 'send_images', :action => 'show_file_by_send', :filepath => "#{APP_CONFIG['remote_file_root_directory']}#{well.montage_url}"), :class => "montage_image sq250"
      %p.ed
        %table
          %tbody
            = table_euclidean_distance(well).html_safe if well.analytical_results.where(name: "Euclidean Distance").exists?
            = comparison_metadata_records(well).html_safe if well.metadata_records.present?
            = comparison_control(well).html_safe if well.is_control?

-#%script
-#  function closeWindow() {window.open('','_parent','');window.close();}

app/views/well_comparisons/edit.html.haml
-#
  Copyright (C) 2014 Juergen Helmers - All Rights Reserved
  You may not use, distribute and modify this code under any
  circumstance without the written permission of the author.

  Juergen Helmers <juergen.helmers@gmail.com>


= form_for @well_comparison, :html => { :class => 'well form-horizontal' } do |f|
  - if @well_comparison.errors.any?
    #error_explanation
      %h2= "#{pluralize(@well_comparison.errors.count, "error")} prohibited this well_comparison from being saved:"
      %ul
        - @well_comparison.errors.full_messages.each do |msg|
          %li= msg
  %fieldset
    %legend
      = controller.action_name.capitalize
      Well Comparison
    .control-group
      = f.label :description, :class => 'control-label'
      .controls
        = f.text_area :description, rows: '1', :class => 'span8', :placeholder => "Well Comparison Description"
        %span.help-inline
          To identify comparisons later, best to add a good description!


    -if @well_comparison.workingwells.present?
      - @well_comparison.workingwells.each do |well|
        -if well.montage_url.present?
          .well_container
            =image_tag url_for(:controller => 'send_images', :action => 'show_file_by_send', :filepath => "#{APP_CONFIG['remote_file_root_directory']}#{well.montage_url}"), :class => "montage_image sq250"
            %p.ed
              %table
                %tbody
                  = table_euclidean_distance(well).html_safe if well.analytical_results.where(name: "Euclidean Distance").exists?
                  = comparison_metadata_records(well).html_safe if well.metadata_records.present?
                  = comparison_control(well).html_safe if well.is_control?


  -if current_user && @well_comparison.user_id == current_user.id || current_user.admin?
    .form-actions
      = link_to 'Back', well_comparisons_path, class: 'btn btn-mini btn-default'
      = f.submit 'Save Comparison', class: 'btn btn-mini btn-success'

app/views/well_comparisons/index.html.haml
%h1 Listing Well Comparisons

-if @well_comparisons.length > 0
  %div.filter
    %p
      = link_to "All Well Comparisons", :action => "index"
      |
      = link_to "My Well Comparisions", :action => "index", :me => "true"

  %table.table.table-striped
    %thead
      %tr
        %th Description
        -unless params[:me]
          %th User
        %th Actions


    - @well_comparisons.each do |well_comparison|
      %tbody
        %tr
          %td= link_to well_comparison.description, well_comparison, class: "popover_link", data: {animation: "true", placement: "right", trigger: "hover", html: "true", title: "Wells",content: "#{popover_comparison(well_comparison)}"}
          - unless params[:me]
            %td= well_comparison.user.username unless params[:me]
          %td
            -#= link_to 'Show', well_comparison, class: 'btn btn-mini'
            -if well_comparison.user_id == current_user.id || current_user.admin?
              = link_to 'Edit', edit_well_comparison_path(well_comparison), class: 'btn btn-mini btn-success'
              = link_to 'Delete', well_comparison, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-mini btn-danger'
            -else
              %button.btn.btn-mini.bn-success.disabled Edit
              %button.btn.btn-mini.btn-danger.disabled Delete

-else
  %p
    There are currently no well comparison on record.

app/views/well_comparisons/new.html.haml
= render 'form'

app/views/well_comparisons/show.html.haml
-#
  Copyright (C) 2012 Juergen Helmers - All Rights Reserved
  You may not use, distribute and modify this code under any
  circumstance without the written permission of the author.

  Juergen Helmers <juergen.helmers@gmail.com>


%h1 Well Comparison
%dl.show.dropshadow.raised


  %dt Description
  %dd= @well_comparison.description

  %dt User
  %dd= @well_comparison.user.fullname
.clear
-if @well_comparison.workingwells.present?
  - @well_comparison.workingwells.each do |well|
    -if well.montage_url.present?
      .well_container
        =image_tag url_for(:controller => 'send_images', :action => 'show_file_by_send', :filepath => "#{APP_CONFIG['remote_file_root_directory']}#{well.montage_url}"), :class => "montage_image sq250"
        %p.ed
          %table
            %tbody
              = table_euclidean_distance(well).html_safe if well.analytical_results.where(name: "Euclidean Distance").exists?
              = comparison_metadata_records(well).html_safe if well.metadata_records.present?
              = comparison_control(well).html_safe if well.is_control?
              %tr
                %td
                %td= link_to 'view with controls', compare_with_control_well_comparison_path(well), class: "btn btn-mini", target: "_blank"

.clear
.form-actions
  = link_to 'Back', well_comparisons_path, class: 'btn btn-mini'
  -if current_user && @well_comparison.user_id == current_user.id || current_user.admin?
    = link_to 'Edit', edit_well_comparison_path(@well_comparison), :class => 'btn btn-mini'
    = link_to 'Delete', well_comparison_path(@well_comparison), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger'